import { StyleSheet } from 'react-native';
import { THEME } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.colors.bgDark,
    justifyContent: 'center',
    alignItems: 'center',
  },
  glowOrb: {
    position: 'absolute',
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(56, 189, 248, 0.12)',
  },
  content: {
    alignItems: 'center',
    paddingHorizontal: 30,
    width: '100%',
  },
  logoWrapper: {
    width: 120,
    height: 120,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  outerRing: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: 2,
    borderColor: 'transparent',
    borderTopColor: THEME.colors.accentCyan,
    borderRightColor: THEME.colors.accentBlue,
  },
  logoBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: THEME.colors.bgCardElevated,
    borderWidth: 1.5,
    borderColor: THEME.colors.accentCyan,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 10,
    shadowColor: THEME.colors.accentCyan,
    shadowOpacity: 0.5,
    shadowRadius: 15,
  },
  logoEmoji: {
    fontSize: 34,
  },
  appTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: THEME.colors.textPrimary,
    letterSpacing: -0.5,
  },
  appSubtitle: {
    fontSize: 13,
    color: THEME.colors.textSecondary,
    marginTop: 6,
    textAlign: 'center',
  },
  brandBadge: {
    marginTop: 24,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: 'rgba(21, 33, 56, 0.8)',
    borderWidth: 1,
    borderColor: 'rgba(56, 189, 248, 0.3)',
    alignItems: 'center',
  },
  brandLabel: {
    fontSize: 9,
    fontWeight: '800',
    color: THEME.colors.accentCyan,
    letterSpacing: 1.5,
  },
  brandName: {
    fontSize: 15,
    fontWeight: '900',
    color: THEME.colors.textPrimary,
    marginTop: 2,
  },
  brandUrl: {
    fontSize: 10,
    color: THEME.colors.textMuted,
    marginTop: 2,
  },
  progressTrack: {
    width: 180,
    height: 4,
    backgroundColor: '#1E293B',
    borderRadius: 2,
    marginTop: 36,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: THEME.colors.accentCyan,
    borderRadius: 2,
  },
  loadingText: {
    fontSize: 11,
    color: THEME.colors.textMuted,
    marginTop: 10,
  },
  skipButton: {
    marginTop: 20,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  skipText: {
    fontSize: 12,
    fontWeight: '600',
    color: THEME.colors.textSecondary,
  },
});
