import { StyleSheet } from 'react-native';
import { THEME } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.colors.bgDark,
  },
  headerBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: THEME.colors.bgCard,
    borderBottomWidth: 1,
    borderBottomColor: THEME.colors.borderSubtle,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '600',
    color: THEME.colors.textMuted,
  },
  statusConnected: {
    color: THEME.colors.accentEmerald,
    fontWeight: '700',
  },
  sensitivityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  sensitivityLabel: {
    fontSize: 11,
    color: THEME.colors.textMuted,
    fontWeight: '600',
  },
  sensitivityPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: THEME.colors.bgSurface,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
  },
  sensitivityPillActive: {
    backgroundColor: THEME.colors.accentBlue,
    borderColor: THEME.colors.accentCyan,
  },
  sensitivityText: {
    fontSize: 11,
    fontWeight: '700',
    color: THEME.colors.textSecondary,
  },
  sensitivityTextActive: {
    color: '#FFFFFF',
  },
  trackpadArea: {
    flex: 1,
    position: 'relative',
    backgroundColor: THEME.colors.bgDark,
    margin: 12,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: THEME.colors.borderSubtle,
    overflow: 'hidden',
  },
  trackpadSurface: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  trackpadHint: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.2)',
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 22,
  },
  scrollStrip: {
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: 36,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderLeftWidth: 1,
    borderLeftColor: THEME.colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  scrollStripText: {
    fontSize: 10,
    fontWeight: '800',
    color: THEME.colors.accentCyan,
    letterSpacing: 2,
    transform: [{ rotate: '90deg' }],
  },
  mouseButtonsRow: {
    flexDirection: 'row',
    height: 72,
    marginHorizontal: 12,
    marginBottom: 8,
    gap: 8,
  },
  mouseButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: THEME.colors.bgCardElevated,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
    elevation: 4,
  },
  mouseButtonPressed: {
    backgroundColor: THEME.colors.accentBlue,
    borderColor: THEME.colors.accentCyan,
    transform: [{ scale: 0.98 }],
  },
  scrollRollerPad: {
    flex: 0.9,
    height: '100%',
    backgroundColor: THEME.colors.bgCardElevated,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    paddingVertical: 4,
  },
  scrollRollerPadActive: {
    borderColor: THEME.colors.accentBlue,
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
  },
  scrollRollerArrow: {
    fontSize: 11,
    color: THEME.colors.accentBlue,
    fontWeight: '900',
  },
  scrollRollerText: {
    fontSize: 9,
    fontWeight: '800',
    color: THEME.colors.textSecondary,
    letterSpacing: 0.8,
    marginVertical: 1,
  },
  scrollRollerSubText: {
    fontSize: 8,
    fontWeight: '700',
    color: THEME.colors.textMuted,
  },
  mouseButtonDivider: {
    display: 'none',
  },
  mouseButtonText: {
    fontSize: 14,
    fontWeight: '700',
    color: THEME.colors.textPrimary,
  },
  mouseButtonSubText: {
    fontSize: 10,
    color: THEME.colors.textMuted,
    marginTop: 2,
  },
});

