import { StyleSheet } from 'react-native';
import { THEME } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: THEME.colors.bgDark,
    paddingHorizontal: 6,
    paddingVertical: 4,
    justifyContent: 'space-between',
  },
  headerBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: THEME.colors.bgCard,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
    marginBottom: 4,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  hostBadge: {
    fontSize: 12,
    fontWeight: '700',
    color: THEME.colors.accentEmerald,
  },
  hostBadgeDisconnected: {
    fontSize: 12,
    fontWeight: '700',
    color: THEME.colors.textMuted,
  },
  modeSelector: {
    flexDirection: 'row',
    backgroundColor: THEME.colors.bgInput,
    borderRadius: 8,
    padding: 2,
    gap: 2,
  },
  modePill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 6,
  },
  modePillActive: {
    backgroundColor: THEME.colors.accentBlue,
  },
  modeText: {
    fontSize: 11,
    fontWeight: '600',
    color: THEME.colors.textSecondary,
  },
  modeTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  rotateButton: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: THEME.colors.bgSurface,
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
  },
  rotateButtonText: {
    fontSize: 11,
    fontWeight: '600',
    color: THEME.colors.accentBlue,
  },
  macroRibbonWrapper: {
    height: 36,
    maxHeight: 36,
    flexGrow: 0,
    flexShrink: 0,
    marginBottom: 4,
  },
  macroRibbonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 2,
  },
  macroPill: {
    height: 30,
    paddingHorizontal: 12,
    backgroundColor: THEME.colors.bgCardElevated,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
    justifyContent: 'center',
    alignItems: 'center',
  },
  macroPillText: {
    color: THEME.colors.textSecondary,
    fontSize: 11,
    fontWeight: '600',
  },
  quickActionBar: {
    flexDirection: 'row',
    paddingVertical: 4,
    gap: 5,
  },
  quickActionKey: {
    paddingHorizontal: 9,
    paddingVertical: 6,
    backgroundColor: THEME.colors.bgCardElevated,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionText: {
    fontSize: 11,
    fontWeight: '700',
    color: THEME.colors.accentCyan,
  },
  keyboardSurface: {
    flex: 1,
    justifyContent: 'center',
    gap: 3,
  },
  row: {
    flexDirection: 'row',
    gap: 3,
    justifyContent: 'center',
    flex: 1,
  },
  keyWrapper: {
    flex: 1,
    margin: 1.5,
  },
  keySurface: {
    flex: 1,
    backgroundColor: THEME.colors.bgKey,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: 0, height: 2 },
  },
  specialKeySurface: {
    backgroundColor: THEME.colors.bgSurface,
    borderColor: 'rgba(59, 130, 246, 0.15)',
  },
  arrowKeySurface: {
    backgroundColor: THEME.colors.bgSurface,
    borderWidth: 1.5,
    borderColor: 'rgba(59, 130, 246, 0.4)',
    elevation: 4,
  },
  arrowKeyText: {
    fontSize: 18,
    fontWeight: '900',
    color: THEME.colors.accentBlue,
  },
  capsIndicatorDot: {
    position: 'absolute',
    top: 5,
    left: 7,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  capsIndicatorDotActive: {
    backgroundColor: '#10B981',
    shadowColor: '#10B981',
    shadowOpacity: 0.9,
    shadowRadius: 4,
  },
  landscapeOverlayContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    zIndex: 9999,
    backgroundColor: THEME.colors.bgDark,
    justifyContent: 'space-between',
    padding: 6,
  },
  modShiftActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.25)',
    borderColor: THEME.colors.accentBlue,
  },
  modCtrlActive: {
    backgroundColor: 'rgba(99, 102, 241, 0.25)',
    borderColor: THEME.colors.accentIndigo,
  },
  modAltActive: {
    backgroundColor: 'rgba(168, 85, 247, 0.25)',
    borderColor: THEME.colors.accentPurple,
  },
  modGuiActive: {
    backgroundColor: 'rgba(245, 158, 11, 0.25)',
    borderColor: THEME.colors.accentAmber,
  },
  keyText: {
    color: THEME.colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  keyTextSpecial: {
    color: THEME.colors.accentBlue,
    fontSize: 12,
    fontWeight: '600',
  },
  keyTextActive: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  shiftSubText: {
    fontSize: 9,
    color: THEME.colors.textMuted,
    position: 'absolute',
    top: 2,
    right: 4,
  },
  activeKeyToast: {
    position: 'absolute',
    top: 50,
    alignSelf: 'center',
    backgroundColor: 'rgba(26, 28, 35, 0.95)',
    paddingHorizontal: 14,
    paddingVertical: 5,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: THEME.colors.borderMedium,
    zIndex: 100,
  },
  activeKeyToastText: {
    color: THEME.colors.accentBlue,
    fontWeight: '700',
    fontSize: 12,
  },
  key: {
    height: 48,
    flex: 1,
    backgroundColor: THEME.colors.bgKey,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: THEME.colors.borderSubtle,
  },
  specialKey: {
    backgroundColor: THEME.colors.bgSurface,
  },
  keyPressed: {
    backgroundColor: THEME.colors.accentBlue,
    transform: [{ scale: 0.94 }],
  },
});


